---
EnableDefaultLinters: true

exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'

linters:
  AllowedScriptType:
    enabled: true
    allowed_types:
      - 'application/json'
      - 'application/ld+json'
      - 'module'
      - 'text/html'
      - 'text/javascript'
      - 'text/ruby'
      - 'text/template'
    allow_blank: false
    disallow_inline_scripts: false
