require:
  - standard
  # TODO: Add cops later
  # - rubocop-rails
  # - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'build/**/*'
    - 'rubies/**/*'
