---
- :name: 256-jungle
  :title: 256 Jungle
  :background_color: "#1c1c1c"
  :mode: dark
- :name: 3024-night
  :title: 3024 Night
  :background_color: "#090300"
  :mode: dark
- :name: anotherdark
  :title: Anotherdark
  :background_color: "#333333"
  :mode: dark
- :name: asmanian-blood
  :title: Asmanian Blood
  :background_color: "#080404"
  :mode: dark
- :name: autumn
  :title: Autumn
  :background_color: "#ffffff"
  :mode: light
- :name: base16-3024-dark
  :title: Base16 3024 Dark
  :background_color: "#090300"
  :mode: dark
- :name: base16-applepips-dark
  :title: Base16 Applepips Dark
  :background_color: "#374546"
  :mode: dark
- :name: base16-chalk-dark
  :title: Base16 Chalk Dark
  :background_color: "#151515"
  :mode: dark
- :name: base16-default-dark
  :title: Base16 Default Dark
  :background_color: "#151515"
  :mode: dark
- :name: base16-eighties-dark
  :title: Base16 Eighties Dark
  :background_color: "#2d2d2d"
  :mode: dark
- :name: base16-greenscreen-dark
  :title: Base16 Greenscreen Dark
  :background_color: "#001100"
  :mode: dark
- :name: base16-harper-dark
  :title: Base16 Harper Dark
  :background_color: "#010101"
  :mode: dark
- :name: base16-kimbie-dark
  :title: Base16 Kimbie Dark
  :background_color: "#221a0f"
  :mode: dark
- :name: base16-mocha-dark
  :title: Base16 Mocha Dark
  :background_color: "#3b3228"
  :mode: dark
- :name: base16-monokai-dark
  :title: Base16 Monokai Dark
  :background_color: "#272822"
  :mode: dark
- :name: base16-ocean-dark
  :title: Base16 Ocean Dark
  :background_color: "#2b303b"
  :mode: dark
- :name: base16-paraiso-dark
  :title: Base16 Paraiso Dark
  :background_color: "#2f1e2e"
  :mode: dark
- :name: base16-railscasts-dark
  :title: Base16 Railscasts Dark
  :background_color: "#2b2b2b"
  :mode: dark
- :name: base16-solarized-dark
  :title: Base16 Solarized Dark
  :background_color: "#002b36"
  :mode: dark
- :name: base16-solarized-light
  :title: Base16 Solarized Light
  :background_color: "#ffffff"
  :mode: light
- :name: base16-tomorrow-dark
  :title: Base16 Tomorrow Dark
  :background_color: "#1d1f21"
  :mode: dark
- :name: birds-of-paradise
  :title: Birds Of Paradise
  :background_color: "#372725"
  :mode: dark
- :name: blacksea
  :title: Blacksea
  :background_color: "#000000"
  :mode: dark
- :name: borland
  :title: Borland
  :background_color: "#ffffff"
  :mode: light
- :name: brookstream
  :title: Brookstream
  :background_color: "#000000"
  :mode: dark
- :name: busybee
  :title: Busybee
  :background_color: "#151515"
  :mode: dark
- :name: bw
  :title: Bw
  :background_color: "#ffffff"
  :mode: light
- :name: candycode
  :title: Candycode
  :background_color: "#050505"
  :mode: dark
- :name: colorful
  :title: Colorful
  :background_color: "#ffffff"
  :mode: light
- :name: darcula
  :title: Darcula
  :background_color: "#2b2b2b"
  :mode: dark
- :name: dark-z
  :title: Dark Z
  :background_color: "#292929"
  :mode: dark
- :name: dark
  :title: Dark
  :background_color: "#333333"
  :mode: dark
- :name: dark2
  :title: Dark2
  :background_color: "#000000"
  :mode: dark
- :name: darkblue2
  :title: Darkblue2
  :background_color: "#233b5a"
  :mode: dark
- :name: darkbone
  :title: Darkbone
  :background_color: "#000000"
  :mode: dark
- :name: darkburn
  :title: Darkburn
  :background_color: "#3f3f3f"
  :mode: dark
- :name: darkdevel
  :title: Darkdevel
  :background_color: "#000000"
  :mode: dark
- :name: darkerdesert
  :title: Darkerdesert
  :background_color: "#121212"
  :mode: dark
- :name: darkocean
  :title: Darkocean
  :background_color: "#000000"
  :mode: dark
- :name: darkrobot
  :title: Darkrobot
  :background_color: "#1d1d1d"
  :mode: dark
- :name: darkspectrum
  :title: Darkspectrum
  :background_color: "#2a2a2a"
  :mode: dark
- :name: default
  :title: Default
  :background_color: "#f8f8f8"
  :mode: light
- :name: desert
  :title: Desert
  :background_color: "#333333"
  :mode: dark
- :name: deveiate
  :title: Deveiate
  :background_color: "#00000f"
  :mode: dark
- :name: digerati
  :title: Digerati
  :background_color: "#444444"
  :mode: dark
- :name: dim
  :title: Dim
  :background_color: "#000000"
  :mode: dark
- :name: dim2
  :title: Dim2
  :background_color: "#000000"
  :mode: dark
- :name: dracula
  :title: Dracula
  :background_color: "#282a36"
  :mode: dark
- :name: emacs
  :title: Emacs
  :background_color: "#f8f8f8"
  :mode: light
- :name: freya
  :title: Freya
  :background_color: "#2a2a2a"
  :mode: dark
- :name: friendly
  :title: Friendly
  :background_color: "#f0f0f0"
  :mode: light
- :name: fruity
  :title: Fruity
  :background_color: "#111111"
  :mode: dark
- :name: github-dark
  :title: Github Dark
  :background_color: "#161b22"
  :mode: dark
- :name: github-light
  :title: Github Light
  :background_color: "#f5f8fa"
  :mode: light
- :name: gruvbox-dark
  :title: Gruvbox Dark
  :background_color: "#282828"
  :mode: dark
- :name: gruvbox-light
  :title: Gruvbox Light
  :background_color: "#fbf1c7"
  :mode: light
- :name: herald
  :title: Herald
  :background_color: "#151515"
  :mode: dark
- :name: idle-fingers
  :title: Idle Fingers
  :background_color: "#323232"
  :mode: dark
- :name: inkpot
  :title: Inkpot
  :background_color: "#1e1e27"
  :mode: dark
- :name: jellybeans
  :title: Jellybeans
  :background_color: "#151515"
  :mode: dark
- :name: manni
  :title: Manni
  :background_color: "#f0f3f3"
  :mode: light
- :name: monokai
  :title: Monokai
  :background_color: "#272822"
  :mode: dark
- :name: murphy
  :title: Murphy
  :background_color: "#ffffff"
  :mode: light
- :name: mustang
  :title: Mustang
  :background_color: "#202020"
  :mode: dark
- :name: native
  :title: Native
  :background_color: "#202020"
  :mode: dark
- :name: neverland
  :title: Neverland
  :background_color: "#121212"
  :mode: dark
- :name: no-quarter
  :title: No Quarter
  :background_color: "#303030"
  :mode: dark
- :name: pastels-on-dark
  :title: Pastels On Dark
  :background_color: "#2b2b2b"
  :mode: dark
- :name: pastie
  :title: Pastie
  :background_color: "#ffffff"
  :mode: light
- :name: peaksea
  :title: Peaksea
  :background_color: "#202020"
  :mode: dark
- :name: perldoc
  :title: Perldoc
  :background_color: "#eeeedd"
  :mode: light
- :name: railscasts
  :title: Railscasts
  :background_color: "#2b2b2b"
  :mode: dark
- :name: rdark
  :title: Rdark
  :background_color: "#1e2426"
  :mode: dark
- :name: refactor
  :title: Refactor
  :background_color: "#151515"
  :mode: dark
- :name: sahara
  :title: Sahara
  :background_color: "#151515"
  :mode: dark
- :name: slate
  :title: Slate
  :background_color: "#262626"
  :mode: dark
- :name: solarized-dark
  :title: Solarized Dark
  :background_color: "#002b36"
  :mode: dark
- :name: solarized-light
  :title: Solarized Light
  :background_color: "#fdf6e3"
  :mode: light
- :name: synic
  :title: Synic
  :background_color: "#000000"
  :mode: dark
- :name: tango
  :title: Tango
  :background_color: "#f8f8f8"
  :mode: light
- :name: tomorrow-night-blue
  :title: Tomorrow Night Blue
  :background_color: "#002451"
  :mode: dark
- :name: tomorrow-night
  :title: Tomorrow Night
  :background_color: "#1d1f21"
  :mode: dark
- :name: trac
  :title: Trac
  :background_color: "#ffffff"
  :mode: light
- :name: twilight
  :title: Twilight
  :background_color: "#181818"
  :mode: dark
- :name: up
  :title: Up
  :background_color: "#1b1b1b"
  :mode: dark
- :name: vim
  :title: Vim
  :background_color: "#000000"
  :mode: dark
- :name: vitamins
  :title: Vitamins
  :background_color: "#242424"
  :mode: dark
- :name: vs
  :title: Vs
  :background_color: "#ffffff"
  :mode: light
- :name: wombat
  :title: Wombat
  :background_color: "#242424"
  :mode: dark
- :name: zenburn
  :title: Zenburn
  :background_color: "#383838"
  :mode: dark
- :name: zenesque
  :title: Zenesque
  :background_color: "#0f1216"
  :mode: dark
