# Put this in the file: .github/workflows/verify.yml

name: Verify
on: [push]

env:
  RAILS_ENV: test
  ADMIN_EMAIL: admin@example.com
  ADMIN_PASSWORD: secret

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Run linters
        run: |
          bin/standardrb --parallel

      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/brakeman -q -w2

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'
          cache: yarn

      - name: Setup geckodriver
        uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup

      - name: Run tests
        run: bin/rspec

  assets:
    name: Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup

      - name: Make sure assets compile
        run: |
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} \
          SECRET_KEY_BASE_DUMMY=1 \
          RAILS_ENV=production \
          bin/rails assets:precompile
